
import argparse
parser = argparse.ArgumentParser(description='Parsing arguments...')

parser.add_argument('--device',type=str,required=True)
parser.add_argument('--train_size', type=float,required=True)
parser.add_argument('--test_size', type=float,required=True)
parser.add_argument('--val_size',type=float,required=True)
parser.add_argument('--training_duplicates', type=int,required=True)
parser.add_argument('--testing_duplicates',type=int,required=True)
parser.add_argument('--forecast_horizon',type=int,required=True,help='fh, options: [94,192,336,720 ]')
parser.add_argument('--batch_size',type=int,required=True)
parser.add_argument('--n_epochs',type=int,required=True)
parser.add_argument('--past_history',type=int,required=True)
parser.add_argument('--selected_model',type=str,required=True,help='models, options: [Simple_Linear, N_Linear,DLinearModel, Deep_Blocks,DC_BEATS,Autoformer]')
parser.add_argument('--lr',type=float,required=True)
parser.add_argument('--shuffle',action='store_true',default=False)
parser.add_argument('--save_optimal_model', action='store_true',default=False)
parser.add_argument('--kernel_size',type=int,required=True)
parser.add_argument('--num_stacks',type=int,required=True)
parser.add_argument('--num_blocks',type=int,required=True)
parser.add_argument('--fc_hidden_layers',type=int,required=True)
parser.add_argument('--fc_hidden_units',type=int,required=True)
parser.add_argument('--block_sharing',action='store_true',default=False)
parser.add_argument('--dropout',type=float,required=True)
parser.add_argument('--hidden_layers_dropout',type=float,required=True)
parser.add_argument('--dataset_name',type=str,required=True,help='datasets, options: [exchange_rate, ETTh1, ETTh2,national_illness,ETTm1,ETTm2,traffic,weather,electricity]')
parser.add_argument('--num_series', type=int,required=True)
parser.add_argument('--dataset_num_series', type=int,required=True)
parser.add_argument('--data_file_path',type=str,required=True)
parser.add_argument('--exec_name',type=str,required=True)
parser.add_argument('--save_model_PATH',type=str,required=True)

parser.add_argument('--label_len', type=int,required=True)
parser.add_argument('--output_attention', action='store_true',default=False)
parser.add_argument('--embed_type', type=int,required=True)
parser.add_argument('--embed',type=str,required=True)
parser.add_argument('--freq',type=str,required=True)
parser.add_argument('--activation',type=str,required=True)
parser.add_argument('--factor', type=int,required=True)
parser.add_argument('--d_model', type=int,required=True)
parser.add_argument('--n_heads', type=int,required=True)
parser.add_argument('--d_ff', type=int,required=True)
parser.add_argument('--d_layers', type=int,required=True)
parser.add_argument('--e_layers', type=int,required=True)
parser.add_argument('--distil', action='store_true',default=False)
parser.add_argument('--approach',type=str,required=True)
parser.add_argument('--exec_context',type=str,required=True)
parser.add_argument('--exec_iterations', type=int,required=True)
parser.add_argument('--custom_val_split', type=int,required=True)
parser.add_argument('--invs_dataset_aug', type=int,required=True)

args = parser.parse_args()

print("Execution's arguments: ", args)